"""
Configuration management for Earnings Calls Analyzer.

Loads application settings from environment variables
and .env files using Pydantic BaseSettings.
"""

from functools import lru_cache
from typing import Optional

from pydantic_settings import BaseSettings
from pydantic import Field

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="faiss")


class Settings(BaseSettings):
    """Configuration for Earning Calls Analyzer and environment variables management"""

    #App Info and settings
    app_name: str = Field(default="Earning Calls Analyzer", env="APP_NAME")
    app_version: str = Field(default="0.1.0", env="APP_VERSION")
    DEBUG: bool = Field(default=False, env="DEBUG")

    #Database settings
    DATABASE_URL: str = Field(
        default="sqlite:///./earning_calls_analyzer.db", env="DATABASE_URL"
    )
    SQLALCHEMY_ECHO: bool = Field(default=False, env="SQLALCHEMY_ECHO")

    """AWS Configuration Settings:
    1. AWS_ACCESS_KEY_ID: AWS Access Key ID for authentication.
    2. AWS_SECRET_ACCESS_KEY: AWS Secret Access Key for authentication.
    3. AWS_REGION: AWS Region where the services are hosted.
    4. AWS bedrock: AWS Bedrock is a service that provides foundational models for various AI applications. It allows users to access and utilize pre-trained models for tasks such as natural language processing, computer vision, and more. The configuration for AWS Bedrock would typically include the necessary credentials and region information to connect to the service and utilize its capabilities.
    5. BEDROCK_EMBEDDING_MODEL: This setting specifies the embedding model ID to be used with AWS Bedrock. Embedding models are used to convert text into numerical vectors that can be processed by machine learning algorithms. The default value is set to "amazon.titan-embed-text-v2:0", which is a specific embedding model provided by AWS Bedrock.
    6. BEDROCK_LLM_MODEL: This setting specifies the LLM (Language Model) model ID to be used with AWS Bedrock. LLM models are large language models that can perform various natural language processing tasks, such as text generation, summarization, and more. The default value is set to "anthropic.claude-3-sonnet-20240229-v1:0", which is a specific LLM model provided by AWS Bedrock.
    7. VECTOR_DIMENSION: This setting specifies the dimension of the vectors generated by the embedding model. For the Titan v2 embedding model, the dimension is set to 1024.
    8. FAISS_INDEX_DIR: This setting specifies the directory where FAISS indices will
    """

    AWS_ACCESS_KEY_ID: Optional[str] = Field(default=None, env="AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY: Optional[str] = Field(default=None, env="AWS_SECRET_ACCESS_KEY")
    AWS_REGION: Optional[str] = Field(default=None, env="AWS_REGION")

    #Bedrock settings
    BEDROCK_EMBEDDING_MODEL: str = Field(
        default="amazon.titan-embed-text-v2:0",
        description="AWS Bedrock embedding model ID",
    )
    BEDROCK_LLM_MODEL: str = Field(
        default="anthropic.claude-3-sonnet-20240229-v1:0",
        description="AWS Bedrock LLM model ID (Claude)",
    )

    # Vector Store
    VECTOR_DIMENSION: int = 1024  # Titan v2 embedding dimension
    FAISS_INDEX_DIR: str = Field(
        default="./data/indices", description="Directory for FAISS indices"
    )

    #Chunks Settings
    CHUNK_SIZE: int = 500  # tokens per chunk, can be adjusted based on the model's context window and performance requirements
    CHUNK_OVERLAP: int = 50  # tokens

    # API
    API_HOST: str = "0.0.0.0"
    API_PORT: int = 8000
    CORS_ORIGINS: list[str] = ["*"]

    # Logging
    LOG_LEVEL: str = "INFO"
    LOG_FILE: str = "./logs/app.log"

    class Config:
        env_file = ".env"
        case_sensitive = True

@lru_cache()
def get_settings() -> Settings:
    """Get the application configuration with caching for performance."""
    return Settings()

