"""
Configuration management for Earnings Calls Analyzer.

Loads application settings from environment variables
and .env files using Pydantic Settings v2.
AWS Configuration Settings:
    1. AWS_ACCESS_KEY_ID: AWS Access Key ID for authentication.
    2. AWS_SECRET_ACCESS_KEY: AWS Secret Access Key for authentication.
    3. AWS_REGION: AWS Region where the services are hosted.
    4. AWS bedrock: AWS Bedrock is a service that provides foundational models for various AI applications.
    -- It allows users to access and utilize pre-trained models for tasks such as natural language processing, computer vision, and more. 
    -- The configuration for AWS Bedrock would typically include the necessary credentials and region information to connect to the service and utilize its capabilities.
    5. BEDROCK_EMBEDDING_MODEL: This setting specifies the embedding model ID to be used with AWS Bedrock. 
    -- Embedding models are used to convert text into numerical vectors that can be processed by machine learning algorithms. 
    -- The default value is set to "amazon.titan-embed-text-v2:0", which is a specific embedding model provided by AWS Bedrock.
    6. BEDROCK_LLM_MODEL: This setting specifies the LLM (Language Model) model ID to be used with AWS Bedrock.
    -- LLM models are large language models that can perform various natural language processing tasks, such as text generation, summarization, and more. 
    -- The default value is set to "anthropic.claude-3-sonnet-20240229-v1:0", which is a specific LLM model provided by AWS Bedrock.
    7. VECTOR_DIMENSION: This setting specifies the dimension of the vectors generated by the embedding model. For the Titan v2 embedding model, the dimension is set to 1024.
    8. FAISS_INDEX_DIR: This setting specifies the directory where FAISS indices will
"""
from functools import lru_cache
from typing import Optional
import warnings

from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Optional



warnings.filterwarnings("ignore", category=UserWarning, module="faiss")


class Settings(BaseSettings):
    """Application settings."""

    # Pydantic Settings v2 configuration
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )

    # ==================== App Settings ====================

    APP_NAME: str = "Earnings Calls Analyzer"
    APP_VERSION: str = "0.1.0"
    DEBUG: bool = False

    # ==================== Database Settings ====================

    DATABASE_URL: str = "sqlite:///./earning_calls_analyzer.db"
    SQLALCHEMY_ECHO: bool = False
    VECTOR_DB : str = "faiss"  # Options: "faiss", "weaviate", "milvus", "pinecone", "qdrant"

    # ==================== AWS Settings ====================

    AWS_ACCESS_KEY_ID: Optional[str] = None
    AWS_SECRET_ACCESS_KEY: Optional[str] = None
    AWS_REGION: Optional[str] = None

    SUPPORTED_FILE_TYPES = [".pdf"]
    MAX_UPLOAD_SIZE_MB = 50

    ROLE_USER = "user"
    ROLE_ADMIN = "admin"

    DEFAULT_ENCODING = "utf-8"

    # ==================== Model temperature ====================
    LLM_TEMPERATURE: float = 0.7  # Default temperature for LLM responses
    LLM_MAX_TOKENS: int = 2048  # Default max tokens for LLM responses
    # ==================== Bedrock Settings ====================

    BEDROCK_EMBEDDING_MODEL: str = (
        "amazon.titan-embed-text-v2:0"
    )

    BEDROCK_LLM_MODEL: str = (
        "anthropic.claude-3-sonnet-20240229-v1:0"
    )

    # ==================== Vector Store ====================

    VECTOR_DIMENSION: int = 1024

    FAISS_INDEX_DIR: str = "./data/indices"

    # ==================== Chunking ====================

    CHUNK_SIZE: int = 500
    CHUNK_OVERLAP: int = 50

    # ==================== API ====================

    API_HOST: str = "0.0.0.0"
    API_PORT: int = 8000

    CORS_ORIGINS: list[str] = ["*"]

    # ==================== Logging ====================

    LOG_LEVEL: str = "INFO"
    LOG_FILE: str = "./logs/app.log"
    LOG_DIR: str = "./logs"
    LOG_MAX_BYTES: int = 100 * 1024 * 1024  # 100 MB
    LOG_BACKUP_COUNT: int = 5  # Number of backup log files to keep

    UPLOAD_DIR: str = "./data/uploads"

    PROCESSED_DIR: str = "./data/processed"

    CACHE_DIR: str = "./data/cache"

    # ==================== Helper Properties ====================

    @property
    def is_production(self) -> bool:
        """Check if application is running in production."""
        return not self.DEBUG

    @property
    def has_aws_credentials(self) -> bool:
        """Check if AWS credentials are configured."""
        return bool(
            self.AWS_ACCESS_KEY_ID
            and self.AWS_SECRET_ACCESS_KEY
            and self.AWS_REGION
        )

    # ==================== Authentication ====================

    # Secret used for signing JWTs. Should be set in environment for production.
    AUTH_SECRET: str = "change-me"
    # Access token lifetime in minutes
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60


@lru_cache
def get_settings() -> Settings:
    """
    Return a cached Settings instance.

    Prevents reloading .env and environment variables
    on every request.
    """
    return Settings()


# Singleton settings instance

settings = get_settings()